export const WERKBANK_CSS = `
.pb-werkbank{--pb-dur-enter:.55s;--pb-enter-x:-18px;--pb-enter-y:0px;--pb-ease-out:cubic-bezier(.22,1,.36,1);--pb-hero-dur:.55s;--pb-hero-y:0px;--pb-hero-scale:.98;position:relative;background:var(--pb-canvas);color:var(--pb-ink);font-family:var(--pb-font-body);line-height:1.5;overflow-x:clip}
.pb-werkbank *{box-sizing:border-box}.pb-werkbank a{color:inherit;text-decoration:none}.pb-werkbank .muted{color:var(--pb-muted)}
.pb-wb-rail{position:absolute;inset:0 auto 0 0;width:58px;background:var(--pb-ink);color:var(--pb-canvas);display:flex;align-items:center;justify-content:center;z-index:40}
.pb-wb-rail b{writing-mode:vertical-rl;transform:rotate(180deg);font:400 10px/1 var(--pb-font-utility);letter-spacing:.32em;text-transform:uppercase}
.pb-wb-main{margin-left:58px}.pb-wb-nav{position:sticky;top:0;z-index:30;background:color-mix(in srgb,var(--pb-canvas) 94%,transparent);border-bottom:2px solid var(--pb-ink);display:flex;align-items:center;gap:20px;padding:18px clamp(20px,3vw,42px);font:700 11px/1 var(--pb-font-utility);text-transform:uppercase;letter-spacing:.08em;backdrop-filter:blur(8px)}
.pb-wb-logo{font-family:var(--pb-font-display);font-size:17px}.pb-wb-logo img{display:block;max-height:30px;max-width:180px}.pb-wb-nav-links{display:flex;gap:18px;margin-left:auto}
.pb-wb-nav-links a{transition:color .18s}.pb-wb-nav-links a:focus-visible{color:var(--pb-accent-text)}.pb-wb-nav-links a[aria-current="page"]{text-decoration:underline;text-decoration-color:var(--pb-accent);text-underline-offset:5px}
.pb-wb-hero{position:relative;min-height:min(760px,82vh);padding:clamp(48px,7vw,104px) clamp(20px,3vw,42px) 110px;overflow:hidden}
.pb-wb-hero h1{position:relative;z-index:2;margin:0;font-family:var(--pb-font-display);font-size:var(--pb-hero-size);line-height:.84;text-transform:uppercase;max-width:12ch;letter-spacing:-.035em}
.pb-wb-hero h1 span{display:block}.pb-wb-hero .outline{color:transparent;-webkit-text-stroke:2px var(--pb-ink)}.pb-wb-hero .accent{color:var(--pb-accent-text)}
.pb-wb-hero>p{position:relative;z-index:2;max-width:44ch;margin-top:24px}.pb-wb-photo{position:absolute;right:0;top:0;width:39%;height:88%;object-fit:cover;filter:saturate(.72) contrast(1.08);clip-path:polygon(22% 0,100% 0,100% 100%,0 100%);border-left:10px solid var(--pb-accent)}
.pb-werkbank a.pb-wb-cta{position:relative;z-index:2;display:inline-flex;margin-top:30px;background:var(--pb-accent);color:var(--pb-ink);padding:15px 25px;font:700 11px/1 var(--pb-font-utility);text-transform:uppercase;letter-spacing:.08em;transition:transform .2s}.pb-werkbank a.pb-wb-cta:focus-visible{transform:translate(4px,-4px)}
.pb-wb-marquee{position:relative;z-index:3;background:var(--pb-ink);color:var(--pb-canvas);transform:rotate(-1.5deg);margin:-32px -4% 0;padding:14px 0;white-space:nowrap;overflow:hidden;font:400 14px/1 var(--pb-font-display);text-transform:uppercase;letter-spacing:.1em}.pb-wb-marquee-track{display:flex;width:max-content;will-change:transform;animation:pb-wb-marquee 28s linear infinite}.pb-wb-marquee-group{display:flex;flex:none;align-items:center}.pb-wb-marquee-group>span{display:inline-block}.pb-wb-marquee em{font-style:normal;color:var(--pb-accent);padding:0 18px}
.pb-wb-section{padding:clamp(64px,9vw,128px) clamp(20px,4vw,64px);border-top:1px solid var(--pb-line)}.pb-wb-section h2{margin:0;font-family:var(--pb-font-display);text-transform:uppercase;font-size:clamp(2.5rem,6vw,6.5rem);line-height:.88;letter-spacing:-.03em}
.pb-wb-section-head{display:flex;flex-direction:column;gap:14px}.pb-wb-kicker,.pb-wb-step{font:700 10px/1.2 var(--pb-font-utility);text-transform:uppercase;letter-spacing:.18em}.pb-wb-section-head>p{font:400 11px/1.4 var(--pb-font-utility);text-transform:uppercase;letter-spacing:.08em;color:var(--pb-muted)}
.pb-wb-process{display:grid;grid-template-columns:minmax(210px,4fr) minmax(0,8fr);gap:clamp(38px,7vw,110px)}.pb-wb-process .pb-wb-section-head{position:sticky;top:96px;align-self:start}.pb-wb-process-list{border-top:2px solid var(--pb-ink)}
.pb-wb-process .pb-wb-section-head h2{font-size:clamp(2.4rem,3.6vw,4.6rem);max-width:100%}
.pb-wb-service{position:relative;display:grid;grid-template-columns:clamp(70px,9vw,130px) minmax(0,1fr) auto;gap:clamp(16px,3vw,42px);padding:28px 0;border-bottom:1px solid var(--pb-line);align-items:start}.pb-wb-process .pb-wb-service:after{content:"";position:absolute;inset:auto 0 -1px 0;height:2px;background:var(--pb-accent);transform:scaleX(0);transform-origin:left;animation:pb-wb-gauge .65s var(--pb-ease-out) both}.pb-wb-process .pb-wb-service:nth-child(2):after{animation-delay:.1s}.pb-wb-process .pb-wb-service:nth-child(3):after{animation-delay:.2s}.pb-wb-process .pb-wb-service:nth-child(4):after{animation-delay:.3s}
.pb-wb-service .idx{font:400 clamp(2.8rem,6vw,6.6rem)/.8 var(--pb-font-display);color:var(--pb-accent-text);letter-spacing:-.06em}.pb-wb-process .pb-wb-service .idx{animation:pb-wb-index-set .55s var(--pb-ease-out) both}.pb-wb-process .pb-wb-service:nth-child(2) .idx{animation-delay:.1s}.pb-wb-process .pb-wb-service:nth-child(3) .idx{animation-delay:.2s}.pb-wb-process .pb-wb-service:nth-child(4) .idx{animation-delay:.3s}.pb-wb-service-copy{min-width:0}.pb-wb-service h3{margin:6px 0 0;font:400 clamp(1.35rem,2.5vw,2.3rem)/1 var(--pb-font-display);text-transform:uppercase}.pb-wb-service p{max-width:52ch;margin-top:12px}.pb-wb-service .price{font:700 11px/1 var(--pb-font-utility);white-space:nowrap}.pb-wb-step{color:var(--pb-muted)}
.pb-wb-material{background:var(--pb-ink);color:var(--pb-canvas);border-top:10px solid var(--pb-accent)}.pb-wb-material .pb-wb-section-head{display:grid;grid-template-columns:4fr 8fr;gap:30px;margin-bottom:clamp(44px,7vw,88px)}.pb-wb-material h2{color:var(--pb-accent)}.pb-wb-material .pb-wb-kicker{padding-top:8px}
.pb-wb-about{display:grid;grid-template-columns:5fr 7fr;gap:clamp(32px,7vw,110px);align-items:end}.pb-wb-about-copy{position:relative;padding-top:54px}.pb-wb-about-copy p{font-size:clamp(1.25rem,2.3vw,2.25rem);line-height:1.35;max-width:29ch}.pb-wb-about-copy small{display:block;margin-top:48px;font:400 10px/1.4 var(--pb-font-utility);text-transform:uppercase;letter-spacing:.14em;color:var(--pb-accent)}.pb-wb-cross{position:absolute;top:0;font:400 44px/1 var(--pb-font-display);color:var(--pb-accent)}
.pb-wb-about-figure{margin:0}.pb-wb-about-img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover;filter:saturate(.65) contrast(1.1);border-left:10px solid var(--pb-accent)}.pb-wb-about-figure figcaption{margin-top:10px;font:400 10px/1 var(--pb-font-utility);letter-spacing:.12em;text-transform:uppercase;color:var(--pb-accent)}
.pb-wb-workpieces .pb-wb-section-head{display:grid;grid-template-columns:4fr 8fr;gap:30px;margin-bottom:clamp(48px,8vw,100px)}.pb-wb-workpieces .pb-wb-kicker{padding-top:8px}.pb-wb-gallery{display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:clamp(16px,3vw,42px);align-items:start}.pb-wb-gallery figure{margin:0}.pb-wb-gallery figure:nth-child(4n+1){grid-column:1/span 7}.pb-wb-gallery figure:nth-child(4n+2){grid-column:9/span 4;margin-top:clamp(48px,10vw,150px)}.pb-wb-gallery figure:nth-child(4n+3){grid-column:2/span 4}.pb-wb-gallery figure:nth-child(4n+4){grid-column:7/span 6;margin-top:clamp(20px,4vw,60px)}
.pb-wb-image-frame{position:relative;overflow:hidden;background:var(--pb-ink)}.pb-wb-image-frame img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover;filter:saturate(.68) contrast(1.08);transition:transform .55s}.pb-wb-gallery figure:nth-child(even) img{aspect-ratio:3/4}.pb-wb-image-frame>span{position:absolute;right:0;bottom:0;padding:8px 10px;background:var(--pb-accent);color:var(--pb-ink);font:700 10px/1 var(--pb-font-utility)}
.pb-wb-gallery figcaption{display:flex;justify-content:space-between;gap:16px;margin-top:10px;font:400 10px/1.3 var(--pb-font-utility);text-transform:uppercase;letter-spacing:.08em}.pb-wb-gallery figcaption span{color:var(--pb-muted);text-align:right}
.pb-wb-proof{display:grid;grid-template-columns:4fr 8fr;gap:clamp(38px,7vw,110px);background:var(--pb-surface)}.pb-wb-proof .pb-wb-section-head{align-self:start}.pb-wb-proof-grid{display:grid;grid-template-columns:1fr 1fr;border-top:2px solid var(--pb-ink)}.pb-wb-proof blockquote{position:relative;margin:0;padding:28px 26px 30px 0;border-bottom:1px solid var(--pb-line)}.pb-wb-proof blockquote:nth-child(even){padding-left:26px;border-left:1px solid var(--pb-line)}.pb-wb-quote-index{display:block;margin-bottom:10px;font:700 10px/1 var(--pb-font-utility);color:var(--pb-accent-text)}.pb-wb-proof .pb-review-stars{margin:0 0 18px}.pb-wb-proof blockquote p{margin:0 0 28px;font:400 clamp(1.2rem,2vw,1.8rem)/1.3 var(--pb-font-display)}.pb-wb-proof blockquote footer{display:flex;justify-content:flex-start;gap:14px;font:400 10px/1.3 var(--pb-font-utility);text-transform:uppercase;letter-spacing:.08em}.pb-wb-proof .pb-review-avatar{border-radius:0;background:var(--pb-ink);color:var(--pb-canvas);border-color:var(--pb-ink)}.pb-wb-proof .pb-review-source{letter-spacing:.1em}
.pb-wb-contact-sheet{background:var(--pb-accent);color:var(--pb-ink);border-top:0}.pb-wb-contact-head{position:relative;border-bottom:3px solid var(--pb-ink);padding-bottom:clamp(40px,6vw,80px)}.pb-wb-contact-head h2{max-width:10ch;margin-top:24px;font-size:clamp(3.5rem,10vw,11rem)}.pb-wb-contact-mark{position:absolute;right:0;bottom:34px;font:400 clamp(3rem,8vw,8rem)/1 var(--pb-font-display)}.pb-wb-contact-grid{display:grid;grid-template-columns:7fr 5fr;gap:clamp(40px,8vw,120px);padding-top:44px}.pb-wb-contact-links{display:flex;flex-direction:column}.pb-wb-contact-links>a,.pb-wb-contact-links address{display:flex;flex-direction:column;align-items:flex-start;padding:16px 0;border-bottom:1px solid currentColor;font-style:normal;font:400 clamp(1.2rem,2.4vw,2.2rem)/1.2 var(--pb-font-display)}.pb-wb-contact-links small{margin-bottom:7px;font:700 9px/1 var(--pb-font-utility);letter-spacing:.14em;text-transform:uppercase}.pb-wb-hours-block h3{margin:0 0 14px;font:700 10px/1 var(--pb-font-utility);letter-spacing:.14em;text-transform:uppercase}.pb-wb-hours{width:100%;border-collapse:collapse}.pb-wb-hours td{padding:9px 0;border-bottom:1px solid color-mix(in srgb,var(--pb-ink) 35%,transparent);font-size:13px}.pb-wb-hours td:first-child{font-family:var(--pb-font-utility);text-transform:uppercase}.pb-wb-hours td:last-child{text-align:right}
.pb-wb-section:not(.pb-wb-process):not(.pb-wb-material):not(.pb-wb-workpieces):not(.pb-wb-proof):not(.pb-wb-contact-sheet)>.pb-wb-service{grid-template-columns:minmax(0,1fr) auto}.pb-wb-section:not(.pb-wb-process)>.pb-wb-service .idx{font-size:14px}.pb-wb-section>div>h3{margin-top:28px;font-family:var(--pb-font-display);text-transform:uppercase}
.pb-wb-footer{display:grid;grid-template-columns:1fr auto auto;gap:24px;background:var(--pb-ink);color:var(--pb-canvas);padding:38px clamp(20px,4vw,64px);font:400 11px/1.4 var(--pb-font-utility);text-transform:uppercase;letter-spacing:.06em}.pb-wb-footer a{text-decoration:underline;text-underline-offset:3px;opacity:.75}.pb-wb-footer a:focus-visible{opacity:1}
.pb-wb-page-header{padding:64px 6vw 40px;border-bottom:2px solid var(--pb-ink)}.pb-wb-page-header h1{font-family:var(--pb-font-display);font-size:clamp(2.8rem,7vw,7rem);line-height:.9;text-transform:uppercase}.pb-wb-page-header p{margin-top:20px;max-width:60ch;color:var(--pb-muted)}
@keyframes pb-wb-marquee{to{transform:translateX(-50%)}}@keyframes pb-wb-index-set{from{transform:translateX(-18px)}to{transform:none}}@keyframes pb-wb-gauge{to{transform:scaleX(1)}}
@media(hover:hover) and (pointer:fine){.pb-wb-nav-links a:hover{color:var(--pb-accent-text)}.pb-werkbank a.pb-wb-cta:hover{transform:translate(4px,-4px)}.pb-wb-gallery figure:hover img{transform:scale(1.025)}.pb-wb-footer a:hover{opacity:1}}
@media(max-width:960px) and (min-width:841px){
  .pb-wb-process{grid-template-columns:1fr}.pb-wb-process .pb-wb-section-head{position:static;margin-bottom:42px}.pb-wb-process .pb-wb-section-head h2{font-size:clamp(3.5rem,10vw,6rem)}
}
@media(max-width:840px){
  .pb-wb-rail{position:relative;width:100%;height:30px;justify-content:flex-start;padding:0 18px}.pb-wb-rail b{writing-mode:horizontal-tb;transform:none;font-size:9px;white-space:nowrap}.pb-wb-main{margin-left:0}.pb-wb-nav{padding:15px 18px}.pb-wb-nav-links{display:none}
  .pb-wb-hero{display:flex;flex-direction:column;min-height:0;padding:42px 18px 52px;overflow:visible}.pb-wb-hero h1{font-size:clamp(3rem,15vw,5.8rem);line-height:.92;max-width:100%;overflow-wrap:anywhere}.pb-wb-hero h1 span{padding-block:.03em}.pb-wb-hero>p{line-height:1.5;overflow:visible}.pb-wb-photo{position:relative;order:4;width:calc(100% + 36px);height:auto;aspect-ratio:4/3;margin:38px -18px -52px;clip-path:polygon(10% 0,100% 0,100% 100%,0 100%);border-left-width:7px}.pb-wb-marquee{margin:0;padding:11px 0;transform:rotate(-.8deg);font-size:12px}
  .pb-wb-section{padding:64px 18px}.pb-wb-section h2{font-size:clamp(2.8rem,14vw,5rem)}.pb-wb-process,.pb-wb-proof{display:block}.pb-wb-process .pb-wb-section-head{position:static;margin-bottom:40px}.pb-wb-service{grid-template-columns:66px minmax(0,1fr);gap:16px;padding:24px 0}.pb-wb-service .idx{font-size:3.2rem}.pb-wb-service .price{grid-column:2;padding:0}
  .pb-wb-material .pb-wb-section-head,.pb-wb-workpieces .pb-wb-section-head{display:flex;margin-bottom:42px}.pb-wb-about{grid-template-columns:1fr;gap:40px}.pb-wb-about-figure{order:-1}.pb-wb-about-copy p{font-size:1.3rem}
  .pb-wb-gallery{grid-template-columns:1fr;gap:44px}.pb-wb-gallery figure:nth-child(n){grid-column:auto;margin-top:0}.pb-wb-gallery figure:nth-child(even) img{aspect-ratio:4/3}.pb-wb-proof-grid{grid-template-columns:1fr;margin-top:42px}.pb-wb-proof blockquote:nth-child(even){padding-left:0;border-left:0}
  .pb-wb-contact-head h2{font-size:clamp(3.5rem,18vw,6.8rem)}.pb-wb-contact-mark{position:static;display:block;margin-top:24px}.pb-wb-contact-grid{grid-template-columns:1fr}.pb-wb-footer{grid-template-columns:1fr;gap:10px}
}
@media(prefers-reduced-motion:reduce){.pb-werkbank *,.pb-werkbank *:before,.pb-werkbank *:after{animation:none!important;scroll-behavior:auto!important;transition-duration:.01ms!important}.pb-wb-marquee-track{transform:none}.pb-werkbank a.pb-wb-cta:hover,.pb-wb-gallery figure:hover img{transform:none}}
`;
