export const MORGENLICHT_CSS = `
.pb-morgenlicht{--pb-dur-enter:.85s;--pb-enter-y:18px;--pb-ease-out:cubic-bezier(.19,1,.22,1);background:var(--pb-canvas);color:var(--pb-ink);font-family:var(--pb-font-body);line-height:1.65;overflow-x:clip}
.pb-morgenlicht *{box-sizing:border-box}.pb-morgenlicht a{color:inherit;text-decoration:none}
.pb-ml-nav{display:flex;align-items:center;gap:24px;position:sticky;top:14px;z-index:30;margin:14px clamp(16px,3vw,42px) 0;padding:12px 16px 12px 24px;border:1px solid color-mix(in srgb,var(--pb-line) 86%,transparent);border-radius:999px;background:color-mix(in srgb,var(--pb-surface) 88%,transparent);box-shadow:0 18px 60px -38px rgba(44,39,34,.5);backdrop-filter:blur(16px);font-size:11px;letter-spacing:.08em;text-transform:uppercase}
.pb-ml-logo{font:600 20px/1 var(--pb-font-display);letter-spacing:.01em;text-transform:none;color:var(--pb-ink)}.pb-ml-nav-links{display:flex;align-items:center;gap:22px;margin-left:auto;flex-wrap:wrap}.pb-ml-nav-links a{transition:color .2s}.pb-ml-nav-links a:focus-visible{color:var(--pb-accent-text)}.pb-ml-nav-links a[aria-current="page"]{text-decoration:underline;text-decoration-color:var(--pb-accent);text-underline-offset:5px}
.pb-morgenlicht a.pb-ml-nav-cta{flex-shrink:0;padding:10px 18px;border-radius:999px;background:var(--pb-accent);color:var(--pb-accent-contrast);font-size:10px;font-weight:600;letter-spacing:.09em;transition:background-color .2s,transform .2s}
.pb-ml-hero{position:relative;min-height:min(790px,calc(100svh - 72px));padding:clamp(92px,12vw,170px) clamp(24px,7vw,110px);overflow:hidden;isolation:isolate;background:radial-gradient(circle at 18% 18%,color-mix(in srgb,var(--pb-surface) 76%,transparent),transparent 42%)}
.pb-ml-blob{position:absolute;z-index:-2;inset:clamp(48px,6vw,84px) 0 clamp(48px,6vw,84px) 52%;width:48%;height:calc(100% - clamp(96px,12vw,168px));object-fit:cover;object-position:center;border-radius:clamp(90px,12vw,190px) 0 0 clamp(90px,12vw,190px);filter:saturate(.72) sepia(.08) contrast(.95)}
.pb-ml-hero::after{content:"";position:absolute;z-index:-1;inset:0;background:linear-gradient(90deg,var(--pb-canvas) 0%,var(--pb-canvas) 43%,color-mix(in srgb,var(--pb-canvas) 62%,transparent) 58%,transparent 78%);pointer-events:none}
.pb-ml-hero h1{position:relative;max-width:9.5ch;margin:0;font:600 var(--pb-hero-size)/.96 var(--pb-font-display);letter-spacing:-.035em;text-wrap:balance}.pb-ml-hero h1 em{font-weight:500;color:var(--pb-accent-text)}
.pb-ml-hero>p{position:relative;max-width:42ch;margin:26px 0 0;color:var(--pb-muted);font-size:15px}.pb-morgenlicht a.pb-ml-cta{position:relative;display:inline-flex;margin-top:34px;padding:14px 24px;border:1px solid var(--pb-accent);border-radius:999px;background:var(--pb-accent);color:var(--pb-accent-contrast);font-size:11px;font-weight:600;letter-spacing:.1em;text-transform:uppercase;transition:background-color .2s,color .2s,transform .2s}
.pb-ml-float{position:absolute;z-index:3;right:clamp(18px,4vw,64px);min-width:180px;padding:14px 17px;border:1px solid color-mix(in srgb,var(--pb-line) 75%,transparent);border-radius:14px;background:color-mix(in srgb,var(--pb-surface) 88%,transparent);box-shadow:0 18px 50px -30px rgba(44,39,34,.65);backdrop-filter:blur(12px);color:var(--pb-muted);font-size:11px}.pb-ml-float b{display:block;margin-bottom:3px;color:var(--pb-ink);font:600 14px/1.2 var(--pb-font-display)}.pb-ml-float.f1{top:18%;transform:rotate(1.5deg)}.pb-ml-float.f2{bottom:16%;right:clamp(34px,7vw,110px);transform:rotate(-1deg)}
.pb-ml-wave{display:none}.pb-ml-band{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;padding:16px clamp(24px,5vw,72px);border-block:1px solid var(--pb-line);background:var(--pb-surface)}.pb-ml-chip{padding:8px 14px;border:1px solid var(--pb-line);border-radius:999px;color:var(--pb-muted);font-size:10px;letter-spacing:.08em;text-transform:uppercase}
.pb-ml-section{width:min(100%,1400px);margin:0 auto;padding:clamp(76px,10vw,150px) clamp(24px,7vw,110px)}.pb-ml-section h2{max-width:12ch;margin:0 0 clamp(36px,6vw,72px);font:600 clamp(2.5rem,5.5vw,5.7rem)/.98 var(--pb-font-display);letter-spacing:-.035em;text-wrap:balance}.pb-ml-intro{max-width:54ch;margin:-42px 0 48px auto;color:var(--pb-muted)}
/* 1px-Fugen-Trick: line-Fläche scheint als Haarlinie durch — Profil-Gaps setzen den Container transparent (designProfileCss). */
.pb-ml-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:1px;background:var(--pb-line)}.pb-ml-card{display:flex;flex-direction:column;align-items:flex-start;min-height:210px;padding:28px;background:var(--pb-surface)}.pb-ml-card strong{display:block;margin-bottom:14px;font:600 1.3rem/1.1 var(--pb-font-display)}.pb-ml-card p{color:var(--pb-muted);font-size:13px}.pb-ml-price{display:inline-block;margin-top:auto;padding-top:20px;color:var(--pb-accent-text);font-size:11px;font-weight:600;letter-spacing:.08em;text-transform:uppercase}
.pb-ml-about{display:grid;grid-template-columns:minmax(0,1.08fr) minmax(280px,.92fr);gap:clamp(44px,9vw,130px);align-items:center}.pb-ml-about>p:only-child{grid-column:1/-1;max-width:64ch}.pb-ml-about-img{display:block;width:100%;aspect-ratio:4/3;object-fit:cover;border-radius:8px clamp(80px,11vw,170px) 8px 8px;filter:saturate(.76) sepia(.06)}.pb-ml-about p{max-width:55ch;color:var(--pb-muted);font-size:15px;line-height:1.85}
.pb-ml-quote{min-height:230px;padding:30px}.pb-ml-quote p{margin:0 0 20px;font:500 1.25rem/1.45 var(--pb-font-display);color:var(--pb-ink)}.pb-ml-quote footer{margin-top:auto;color:var(--pb-muted);font-size:11px;letter-spacing:.05em}.pb-ml-quote .pb-review-stars{margin-bottom:16px}
.pb-ml-faq strong{display:block;margin-bottom:10px;font:600 1.1rem/1.2 var(--pb-font-display)}.pb-ml-gallery{grid-template-columns:1.15fr .85fr;gap:14px;background:transparent}.pb-ml-gallery img{display:block;width:100%;height:clamp(300px,42vw,580px);object-fit:cover;border-radius:8px;filter:saturate(.74) sepia(.05)}.pb-ml-gallery>*:first-child img{border-radius:clamp(70px,9vw,140px) 8px 8px 8px}.pb-ml-gallery>*:last-child{margin-top:clamp(40px,7vw,100px)}
.pb-ml-member{text-align:left}.pb-ml-member img{width:100%;height:260px;object-fit:cover;margin-bottom:16px}.pb-ml-member strong{display:block;font:600 1.1rem/1.2 var(--pb-font-display)}.pb-ml-member p{color:var(--pb-muted);font-size:13px}
.pb-ml-contact{display:grid;grid-template-columns:1fr 1fr;gap:clamp(40px,8vw,120px);align-items:start}.pb-ml-contact address{font-style:normal}.pb-ml-contact p{margin-bottom:12px}.pb-ml-hours-block{max-width:420px}.pb-ml-hours-block h3{margin-bottom:12px;color:var(--pb-accent-text);font-size:10px;letter-spacing:.1em;text-transform:uppercase}.pb-ml-hours{width:100%;border-collapse:collapse}.pb-ml-hours td{padding:11px 0;border-bottom:1px solid var(--pb-line);font-size:13px}.pb-ml-hours td:last-child{text-align:right}
.pb-ml-menu-category{margin-bottom:30px}.pb-ml-menu-category h3{margin-bottom:14px;color:var(--pb-accent-text);font:600 1.1rem/1.2 var(--pb-font-display)}.pb-ml-cta-card{text-align:center;align-items:center}.pb-morgenlicht a[href^="tel:"],.pb-morgenlicht a[href^="mailto:"]{border-bottom:1px solid var(--pb-line);padding-bottom:2px;transition:border-color .2s,color .2s}
.pb-ml-footer{display:flex;justify-content:space-between;gap:18px;flex-wrap:wrap;padding:34px clamp(24px,7vw,110px);border-top:1px solid var(--pb-line);color:var(--pb-muted);font-size:10px;letter-spacing:.06em;text-transform:uppercase}.pb-ml-footer a{border-bottom:1px solid var(--pb-line)}
.pb-ml-practice-dock{position:sticky;top:86px;z-index:28;margin:10px clamp(16px,3vw,42px) 0 auto;width:fit-content;max-width:calc(100% - 32px);display:flex;align-items:center;gap:12px;padding:7px 8px 7px 15px;border:1px solid var(--pb-line);border-radius:999px;background:color-mix(in srgb,var(--pb-surface) 91%,transparent);box-shadow:0 12px 38px -28px rgba(44,39,34,.6);backdrop-filter:blur(12px);color:var(--pb-muted);font-size:11px}.pb-ml-practice-dock a{padding:8px 13px;border-radius:999px;background:var(--pb-accent);color:var(--pb-accent-contrast);font-weight:600;white-space:nowrap}.pb-ml-section,.pb-ml-hero{scroll-margin-top:142px}
@media(hover:hover) and (pointer:fine){.pb-ml-nav-links a:hover{color:var(--pb-accent-text)}.pb-ml-nav-cta:hover,.pb-ml-cta:hover,.pb-ml-practice-dock a:hover{transform:translateY(-2px)}.pb-morgenlicht a[href^="tel:"]:hover,.pb-morgenlicht a[href^="mailto:"]:hover,.pb-ml-footer a:hover{color:var(--pb-accent-text);border-color:var(--pb-accent)}}
@media(prefers-reduced-motion:no-preference){.pb-ml-blob{animation:pb-ml-focus 1.6s cubic-bezier(.2,.7,.25,1) both}.pb-ml-hero h1,.pb-ml-hero>p,.pb-ml-hero>.pb-ml-cta{animation:pb-ml-breathe-in .8s .2s ease-out both}.pb-ml-float{animation:pb-ml-badge-focus .7s .55s ease-out both}}
@keyframes pb-ml-focus{from{transform:scale(1.035);opacity:.55}to{transform:none;opacity:1}}@keyframes pb-ml-breathe-in{from{transform:translateY(10px);opacity:0}to{transform:none;opacity:1}}@keyframes pb-ml-badge-focus{from{opacity:0;transform:translateY(8px)}to{opacity:1}}
@media(max-width:840px){.pb-ml-nav{top:8px;margin:8px 10px 0;padding:10px 12px 10px 16px}.pb-ml-nav-links,.pb-ml-nav-cta{display:none}.pb-morgenlicht .pb-mnav{display:block;position:relative;margin-left:auto;flex-shrink:0}.pb-morgenlicht .pb-mnav-toggle{box-sizing:border-box;list-style:none;display:flex;align-items:center;justify-content:center;width:42px;height:42px;padding:0;border:1px solid var(--pb-line);border-radius:999px;background:var(--pb-surface);color:var(--pb-ink)}.pb-morgenlicht .pb-mnav-toggle::-webkit-details-marker{display:none}.pb-morgenlicht .pb-mnav-icon{display:flex;flex-direction:column;gap:5px;width:19px}.pb-morgenlicht .pb-mnav-icon span{display:block;height:1px;background:currentColor}.pb-morgenlicht .pb-mnav[open] .pb-mnav-icon span:nth-child(1){transform:translateY(6px) rotate(45deg)}.pb-morgenlicht .pb-mnav[open] .pb-mnav-icon span:nth-child(2){opacity:0}.pb-morgenlicht .pb-mnav[open] .pb-mnav-icon span:nth-child(3){transform:translateY(-6px) rotate(-45deg)}.pb-morgenlicht .pb-mnav-panel{position:absolute;top:calc(100% + 8px);right:0;z-index:80;display:flex;flex-direction:column;min-width:min(270px,86vw);padding:7px;border:1px solid var(--pb-line);background:var(--pb-surface)}.pb-morgenlicht .pb-mnav-panel a{display:flex;align-items:center;min-height:44px;padding:8px 14px;font-size:15px}.pb-ml-practice-dock{top:68px;margin-inline:10px;max-width:calc(100% - 20px)}.pb-ml-practice-dock span{min-width:0;overflow-wrap:anywhere}.pb-ml-section,.pb-ml-hero{scroll-margin-top:130px}.pb-ml-hero{display:flex;flex-direction:column;min-height:auto;padding:64px 20px 26px;overflow:visible}.pb-ml-hero::after{background:linear-gradient(180deg,var(--pb-canvas) 0%,color-mix(in srgb,var(--pb-canvas) 76%,transparent) 58%,transparent 82%)}.pb-ml-hero h1{max-width:10ch;font-size:clamp(3.2rem,15vw,5.4rem)}.pb-ml-blob{position:relative;inset:auto;order:10;width:calc(100% + 40px);height:auto;aspect-ratio:4/5;margin:40px -20px 0;border-radius:90px 0 0 0;object-position:62% center}.pb-ml-float{position:static;order:11;width:100%;margin-top:8px;transform:none!important;box-shadow:none}.pb-ml-band{justify-content:flex-start;padding-inline:20px}.pb-ml-section{padding:76px 20px}.pb-ml-section h2{font-size:clamp(2.8rem,14vw,4.7rem);margin-bottom:36px}.pb-ml-intro{margin:0 0 36px}.pb-ml-about{grid-template-columns:1fr;gap:32px}.pb-ml-about-img{order:-1;border-radius:8px 90px 8px 8px}.pb-ml-gallery{grid-template-columns:1fr;gap:12px}.pb-ml-gallery img{height:auto;aspect-ratio:4/3}.pb-ml-gallery>*:last-child{margin-top:0}.pb-ml-contact{grid-template-columns:1fr}.pb-ml-footer{display:block}.pb-ml-footer p{margin-bottom:8px}}
@media(prefers-reduced-motion:reduce){.pb-morgenlicht *,.pb-morgenlicht *::before,.pb-morgenlicht *::after{animation:none!important;transition:none!important;scroll-behavior:auto!important}}
.pb-ml-page-header{padding:90px 7vw 54px;border-bottom:1px solid var(--pb-line)}.pb-ml-page-header h1{font:600 clamp(3rem,7vw,6.5rem)/.96 var(--pb-font-display);letter-spacing:-.035em}.pb-ml-page-header p{margin-top:20px;max-width:60ch;color:var(--pb-muted)}
`;
