/**
 * Unified type exports
 * Import shared types from this single entry point.
 */

export type * from "../drizzle/schema";
export * from "./_core/errors";

// ── Website Generation Types ───────────────────────────

export interface WebsiteSection {
  type: "hero" | "about" | "services" | "testimonials" | "gallery" | "contact" | "cta" | "features" | "faq" | "team" | "menu" | "pricelist";
  headline?: string;
  subheadline?: string;
  content?: string;
  items?: Array<{
    title?: string;
    description?: string;
    icon?: string;
    rating?: number;
    author?: string;
    question?: string;
    answer?: string;
    price?: string | number;
    category?: string;
    imageUrl?: string;
  }>;
  ctaText?: string;
  ctaLink?: string;
  backgroundImage?: string;
}

/**
 * Per-website design tokens generated by AI.
 * These are injected as CSS custom properties to give each site a unique visual identity.
 */
export interface DesignTokens {
  /** Google Fonts: headline font name e.g. "Playfair Display" */
  headlineFont: string;
  /** Google Fonts: body font name e.g. "Inter" */
  bodyFont: string;
  /** Headline font weight e.g. "700" or "900" */
  headlineFontWeight: string;
  /** Letter spacing for headlines e.g. "-0.03em" or "0.05em" */
  headlineLetterSpacing: string;
  /** Line height for body text e.g. "1.7" */
  bodyLineHeight: string;
  /** Border radius style: "none" | "sm" | "md" | "lg" | "full" */
  borderRadius: "none" | "sm" | "md" | "lg" | "full";
  /** Shadow style: "none" | "flat" | "soft" | "dramatic" | "glow" */
  shadowStyle: "none" | "flat" | "soft" | "dramatic" | "glow";
  /** Section spacing: "tight" | "normal" | "spacious" | "ultra" */
  sectionSpacing: "tight" | "normal" | "spacious" | "ultra";
  /** Alternating section background colors [bg1, bg2, bg3] */
  sectionBackgrounds: string[];
  /** Accent color for CTAs, highlights, links */
  accentColor: string;
  /** Primary text color */
  textColor: string;
  /** Background color */
  backgroundColor: string;
  /** Card background color */
  cardBackground: string;
  /** Button style: "filled" | "outline" | "ghost" | "pill" */
  buttonStyle: "filled" | "outline" | "ghost" | "pill";
  /** Visual mood: archetype name for reference */
  archetype: string;
}

export interface WebsiteData {
  id?: number;
  businessName: string;
  tagline: string;
  description: string;
  sections: WebsiteSection[];
  seoTitle: string;
  seoDescription: string;
  footer: {
    text: string;
    links?: Array<{ label: string; href: string }>;
  };
  // Real Google data injected at generation time
  googleRating?: number | null;
  googleReviewCount?: number | null;
  // Per-website design tokens for visual individuality
  designTokens?: DesignTokens;
  // Branding: show "Erstellt mit Pageblitz" in footer (default: true)
  showBranding?: boolean;
}

export interface ColorScheme {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  surface: string;
  text: string;
  textLight: string;
  gradient?: string;
  onPrimary: string;
  onSecondary: string;
  onAccent: string;
  onSurface: string;
  onBackground: string;
  // Dark layout / dark section overrides
  darkBackground?: string;
  lightText?: string;
}

export interface BusinessSearchResult {
  placeId: string;
  name: string;
  address: string;
  phone?: string;
  website?: string;
  rating?: number;
  reviewCount?: number;
  category?: string;
  lat?: number;
  lng?: number;
  openingHours?: string[];
  hasWebsite: boolean;
}
